### PR TITLE
Linux + Windows (MinGW) support (SDL keyboard/mouse input + Carbon stubs)

### PR DESCRIPTION
**Pull request by DanielGibson**
This now kinda works on Linux.
I hope that keyboard and mouse input works as well as before (on Mac), where it now should build
without Carbon as well.
I created stubs for the Mac/Carbon functions that are still used (and that I didn't eliminate yet), some of
them just print a TODO message, some are now slim wrappers about standard libc functions.
I added a case-insensitive `fopen()`-wrapper (`fopen_caseless()`), so the .res files can be openened from RES/DATA/BLA.RES even though the code says res/data/bla.res

The game generally doesn't seem to work terribly well on Linux, based on your gifs it seems like it's less broken on Mac. No idea why really; I'd appreciate if you could test my branch on Mac again to see if I broke anything - I hope it works just as well as yours :-)

Anyway, I think this is a solid base for Linux (and general non-Mac support, I guess making this build on BSDs would be easy and even Windows shouldn't be terribly hard)

### CODE REVIEW

**Comment by DanielGibson** [comment]
Thanks to @rohit-n this branch now also builds (and "works") on Windows, when compiling with MinGW

**Comment by Interrupt** [comment]
Thanks! I'll give this a shot when I'm back from vacation.

**Comment by DanielGibson** [comment]
Ok, enjoy your trip! :-)

**Comment by Interrupt** [comment]
I was able to get this compiling and running on OSX, and was able to turn physics back on to run around that starting room a bit. Double clicks don't seem to be working though, so I can't open that first door.

**Pull request merged**
