### PR TITLE
Use SDL2_mixer 2.0.2 with backport 

### LINKED ISSUE #243: Travis CI is currently failing at build SDL_mixer

### PR DESCRIPTION
**Pull request by Manuel-K**
Apply patch to fix voc magic

This should fix #243, but it might not, as it is untested.

### CODE REVIEW

**Comment by mrikola** [comment]
If this is taken into use, it should IMO also be used for local and AppVeyor builds.

**Comment by Manuel-K** [comment]
I'm not sure if the AppVeyor is testing any of the changes. It seems to use a cached version of SDL2_mixer.

**Comment by mrikola** [comment]
Oh yeah. Crap. This happened before when we needed to add GLEW to the Windows build. Basically our current process for updating cached dependencies on AppVeyor is:
1) Create a PR with caching turned off in `appveyor.yml` to confirm that the non-cached version builds correctly
2) Merge it, and have @Interrupt clear the cache afterwards so it will reset
3) Push a commit to master with caching turned back on

**Comment by Manuel-K** [comment]
Oh what fun. `tar` does not work correctly because the archive contains symlinks.

**Comment by mrikola** [comment]
Would using the `zip`ped source help here?

**Comment by Manuel-K** [comment]
Possibly.

**Comment by Manuel-K** [comment]
Do we have unzip on AppVeyor?

**Comment by mrikola** [comment]
Yeah, 7z is available. It's what used to create the distributable zip file.

**Comment by Manuel-K** [comment]
Not extracting the Xcode directory fixes the AppVeyor build.

**Comment by Interrupt** [comment]
This seems ready to go now, checks are passing. Do we want to merge it in now?

**Comment by Manuel-K** [comment]
I've just booted into Windows. The AppVeyor artifact has digital sounds.

**Comment by Manuel-K** [comment]
Now we need to clear the AppVeyor cache and re-enable caching. 

@Interrupt, as you are the only person that can do the first part, the “we” is technically a “you”. ;-)

**Pull request merged**
