### PR TITLE
Cleanup Gamesrc

### PR DESCRIPTION
**Pull request by inguin**
- Reindent with clang-format
- Fix most compiler warnings

### CODE REVIEW

**Comment by Interrupt** [comment]
This has a build error for me, after merging in the latest changes:

```
src/GameSrc/wrapper.c:1301:70: error: a parameter list without types
      is only allowed in a function definition
    pushbutton_init(1, 0, tolower(REF_STR_VerifyText + 1), (void (*)(u_char))slork, &r);
                                                                     ^
```

**Comment by inguin** [comment]
Oops, that should have been `uchar`, not `u_char`. Fixed now, I wonder why it built cleanly for me.

**Comment by Interrupt** [comment]
I should have merged this before things diverged too much!

**Comment by inguin** [comment]
No worries, I was expecting to rebase this a few times. I'll take care of it this evening (EDT).

**Comment by inguin** [comment]
Rebased on top of latest master.
Unfortunately the big reindent commit isn't as easily verifiable as it used to be. The new logging macros include source line numbers, so an added or removed line break can change the resulting binary.

**Comment by Interrupt** [comment]
Do you think this is safe to merge then? I'm worried about breaking things with huge PRs like this

**Comment by inguin** [comment]
The huge reindent commit is guaranteed to be safe. I diffed the resulting object files; the only one that changes is `setup.c.o`, and that's only due to the line numbers of the `INFO` macros.

The warning fixes should all be pretty straightforward, but of course there's a chance that I screwed up and broke something. I'd appreciate a second pair of eyes having a look at them.

**Pull request merged**
