### PR TITLE
OpenGL Renderer

### PR DESCRIPTION
**Pull request by inguin**
Limitations and bugs:
- ~~Only in fullscreen mode.~~
- ~~No translucency.~~
- ~~Stars are visible through walls, empty space causes "hall of mirrors" effect.~~
- ~~Textures on non-square surfaces are distorted.~~
- ~~Screen flickering near CCTV monitors.~~
- ~~Textures on distant walls and objects are too small.~~
- ~~Sensaround hardware does not work.~~
- ~~Lighting of 3D objects is not correct.~~
- ~~Leaving the full automap with resized window messes up viewport scaling.~~ (#114, not caused by this PR)
- Some relics when switching from fullscreen to normal view.
- Sensaround V1 view is shadowed by fullscreen 3D view.
- EMP grenade effect isn't correct.
- While a player is restored the screen should turn black.
- ~~The monitor with the laser safety override code is transparent.~~

### CODE REVIEW

**Comment by Interrupt** [comment]
Oh man, this is exciting! I wanted to check this out, but had all kinds of issues on OSX. Firstly getting things to find glew.h, then with the multiline strings in Shock.c not compiling, and then further the shaders were too new for my version of OpenGL so I had to downport them to GLES 2. After _all_ of that I had things compiling and running, but then none of the OpenGL surfaces would draw :(

**Comment by inguin** [comment]
Bummer! I can only test on Linux with NVidia, so I'll definitely need help to make this work on Mac and Windows. Also I'm actually a clueless OpenGL n00b, so I just took the [first tutorial I could find](https://open.gl/) and just used whatever was said there. Could you push your changes somewhere? Maybe I can figure out what's wrong.
Raw string literals are C++11, so I figured they were commonly supported by now. They are obviously needless syntactic sugar for those few lines of shader code.

**Comment by inguin** [comment]
Screenshot: https://imgur.com/FPAHag6

**Comment by Interrupt** [comment]
That looks awesome! Not bad at all for a first stab at this.

The bulk of my issues with this PR come from Apple's horrible support of OpenGl on OSX, which mean that I can't use the newer shader syntax that you're using. It might not be a bad thing though, if you switched targets from GL 3.2 to something widely supported like GLES 2.0, you could drop the glew includes and it would run on everything from a computer to a toaster. Being super portable would be awesome. I'll open a branch later with my compiling GLES syntax shaders.

**Comment by inguin** [comment]
@Interrupt Agreed, compatibility is a priority! As I said, I just went with the recommendations in the tutorial, I didn't pick OpenGL 3.2 because porting a 20+ years old game requires the latest shader features (although "latest" doesn't really apply to a specification released in 2009).

Anyway, I did some digging around in the SDL2 source and I managed to get it running with OpenGL 2.0 and GLSL 1.1. Please try my latest commit and let me know if it works for you.

**Comment by Interrupt** [comment]
This compiles on OSX now, after pointing it at that env's <OpenGL/gl.h> header, and runs without any GL errors as far as I can tell. It's drawing somewhere, just not sure where as the GL surfaces don't seem to render:

https://i.imgur.com/jII3mxy.png

It works fine on Linux for me though, testing in a VM:

https://i.imgur.com/zKh2iDw.png

**Comment by Interrupt** [comment]
Got this to render stuff on OSX! It seems like SDL doesn't really support the mixing of SDL_Render and OpenGL contexts well, to get it to draw stuff I did the following in SDLDraw();

```
//SDL_RenderPresent(renderer);
//SDL_RenderClear(renderer);
SDL_GL_SwapWindow(window);
```
Nothing was drawing without SDL_GL_SwapWindow, but the SDL_RenderPresent / Clear was stomping on it before I could swap so those needed to be commented out.

**Comment by inguin** [comment]
That's fantastic! Coexistence with the SDL renderer gave me a headache, too, until I figured out I had to reactivate my own GL context after any renderer operation. In any case, your problem would have been a temporary one, because sooner or later I'll have to start rendering into an offscreen texture (with the selected game resolution) instead of directly into the window.

Now, if only I could figure out how to render other 3D models! In theory this should be straightforward because they all use the same `g3_draw_tmap()` function, but in practice even a simple cube (`_fr_draw_parm_cube()`) looks completely messed up.

**Comment by inguin** [comment]
OK, looks like I was just to stupid to deal with pointers: `g3_draw_tmap()` take an array of pointers to vertices, not a pointer to an array. For floors and walls (and for the C/C++ type system) the two are equivalent, but for 3D objects they are not.

**Comment by inguin** [comment]
Yeah, me too. Their code may look funny, but LG definitely had some brilliant people. Way ahead of their time!
Colored lighting shouldn't be difficult to implement, but based on what? Light sources either need to be in the level data or associated with objects. The lantern would be a great candidate for a feature enhancement, but right now I'm just trying to replicate the original look with better quality and fewer CPU cycles.

**Comment by markkurikola** [comment]
I tried to get this working on Windows. Turns out MinGW ships with headers and libraries for OpenGL 1.3, forcing an external dependency. I then fetched GLEW which let me build, but now the game crashes silently while setting up graphics. I don't have the MSVC setup on the computer I'm currently using; I'll try to get a stack trace and possible fix up once I'm back at that box.

**Comment by inguin** [comment]
@markkurikola If you're including glew.h you'll probably need to add the following to `init_opengl()` after `SDL_GL_CreateContext()`:

```
glewExperimental = GL_TRUE;
glewInit();
```

I tried compiling this with mingw32 and running in wine, but so far without much success. It either crashes right away because the GL context creation fails for mysterious reasons, or I'm getting a black window.

**Comment by mrikola** [comment]
Looks like `glCreateShader` is a null pointer for some reason. I'm thinking something somewhere looks at the Windows default v1.1 implementation and doesn't find it (as it was added in v2.0)

**Comment by inguin** [comment]
With GLEW, all GL functions are pointers that are initially NULL and initialized by `glewInit()`. What's the return code of `glewInit()`? You can display it as follows:

```
GLenum err = glewInit();
if (err != GLEW_OK)
   fprintf(stderr, "glewInit(): %s\n", glewGetErrorString(err));
```

**Comment by mrikola** [comment]
Okay, cool, I fell into _that_ trap. See, my dumb self looked at the nicely running `glEnable`s and figured GLEW was doing just fine.

Console output:
```
WARN: Assertion failure at SDL_GL_CreateContext_REAL (src/video/SDL_video.c:3394), triggered 1 time:
  'window && window->magic == &_this->window_magic'

glewInit(): Missing GL version
```

**Comment by mrikola** [comment]
Okay, part 1 of the problem seems to be solved. The `window` pointer didn't survive the extern definitions it was subjected to, and was `NULL` in OpenGL.cc. I ended up wrapping the `#include "Shock.h"`directive in an `extern "C"`. This fixed problems all the way up to `glewInit()` failing, but still I'm not getting OpenGL v2.0 support. To be continued...

**Comment by Interrupt** [comment]
Maybe we should include the GLM headers, it seems like that's what is breaking the CI at the moment.

**Comment by inguin** [comment]
I could easily hard-code the two matrices and drop the GLM includes. It was convenient to get it right initially, but now it's no longer necessary.

Getting rid of GLM would even allow me to switch from C++ to C, but I had actually planned to use STL containers to implement a texture cache.

**Comment by Interrupt** [comment]
C++ is fine at the margins of the app like this, not everything has to be in C.

**Comment by inguin** [comment]
@mrikola Thanks, I wrapped the includes and extern declarations in an `extern "C"` block, so the `window` pointer should now be correct for you.

My experiments with the mingw32 cross-compiler and Wine were still not very successful:
- The frequent startup crashes seemed to be a race condition. Adding a delay between `SDL_CreateWindow()` and `SDL_GL_CreateContext()` made them go away. Ugly, but maybe only a problem in Wine.
- As soon as I add the `SDL_WINDOW_OPENGL` flag the entire game runs extremely slow.
- Nothing is rendered when I switch to my renderer. :disappointed:

**Comment by mrikola** [comment]
I somehow managed to finagle the code to run on MSVC (by recompiling SDL, I don't know what's up with that), but I'm not seeing any difference when turning OpenGL on. 

MinGW build on my end gives me the same "GL 3.x is not supported" error that I got out of the MSVC build when I put all of the `SDL_GL_SetAttribute` calls into OpenGL.cc.

**Comment by inguin** [comment]
Try removing the `SDL_GL_CONTEXT_PROFILE_MASK` attribute. It's a relic from the tutorial I used for a template, I'm not really sure what it does, and it seems to stop SDL from creating a "legacy" context in line 703 of the file you linked.

**Comment by mrikola** [comment]
Unfortunately the legacy thing only results in a v1.1 context without the error message. It's the same context that the `else` branch also creates, so that it can use `wglGetProcAddress("wglCreateContextAttribsARB")` which seems to return `NULL` for some reason.

**Comment by markkurikola** [comment]
Progress comes in baby steps. I took my coworker's [SDL/OpenGL tester utility](https://github.com/juliusikkala/GLContextTester) and compiled it with MinGW, and it turns out the answer (on this computer, anyway) was MORE specs to the `SDL_GL_SetAttribute` calls. I have no words.

Except for this: now it crashes after the `init.c:378: - Screen init` log.

**Comment by inguin** [comment]
OK, I finally managed to build a tiny OpenGL test program with mingw32 and run it in Wine. Looks like Chad's hypothesis is true: The SDL renderer interface and plain OpenGL don't mix! Creating a renderer right after opening the window causes GL context creation to fail. Creating the renderer after the context results in a black screen.

This really sucks, because as far as I see it means that we cannot easily switch between OpenGL and software rendering. We'd have to reopen a new window each time, either with or without the `SDL_WINDOW_OPENGL` flag. Currently my hope is that I can mix off-screen OpenGL with SDL rendering; that would be good enough.

**Comment by Interrupt** [comment]
It looks like the SDL renderer assumes it knows what the current render state is, if we can reset the render state after OpenGL rendering back to what the SDL renderer wants things could work. More info here: https://discourse.libsdl.org/t/mixing-opengl-and-renderer/19946/20

**Comment by inguin** [comment]
I have a pretty simple theory why this is such a big problem in Windows while it works reasonably well in Linux and OSX: In Windows, the SDL renderer might prefer DirectX over OpenGL, and I have a strong suspicion that those two don't get along very well.

**Comment by Interrupt** [comment]
Maybe we can force Windows to use OpenGL instead with the https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER setting.

**Comment by inguin** [comment]
Setting SDL_HINT_RENDER_DRIVER did the trick, at least with my setup!

**Comment by farmboy0** [comment]
With the latest state of this branch I get graphical corruption during the pause menu.

**Comment by inguin** [comment]
Yeah, that's currently expected. That's one of the issues that will be resolved by rendering into an offscreen texture.

**Comment by TobiasKarnat** [comment]
I did not compile for me first, SDL_PIXELFORMAT_RGBA32 was not found.
After I changed it to SDL_PIXELFORMAT_ABGR8888 (in OpenGL.cc) it works great.

**Comment by inguin** [comment]
@TobiasKarnat `SDL_PIXELFORMAT_RGBA32` was added in SDL2 2.0.5. Changing it to `ABGR8888` is not endian-safe.

**Comment by mrikola** [comment]
Note to @Interrupt: once this is merged, you'll want to turn the `build_ext` caching back on in `appveyor.yml`.

**Comment by TobiasKarnat** [comment]
Side question: Could you also implement optionally internal xBRZ scaling?
fgx8yj8

**Comment by inguin** [comment]
My plan was to add HQX scaling at some point. But xBRZ might also be worth a look.

https://en.wikipedia.org/wiki/Hqx

**Comment by TobiasKarnat** [comment]
xBRZ looks and performs better than HQx:
https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms#xBR_family

**Comment by inguin** [comment]
Agreed, it looks pretty damn good in the comparison chart.

**Comment by AcceptableSpare** [comment]
Hmm just did a quick test of it on windows 10 /w my 960 gtx.

EMP grenade effect isn't correct
When a player is restored the screen should turn black and not show the last screen when they died
There's a one pixel tall line between a bulkhead door when it's opened
The polygon sorting for one of the monitors in the library is incorrect on the Research Labs. You can see the screen text, but can't see parts of the monitor at all.

**Comment by inguin** [comment]
> *EMP grenade effect isn't correct
> *When a player is restored the screen should turn black and not show the last screen when they died
> *The monitor with the laser safety override code should have a background on it rather than being able to see through it (text should be red and background black when compared to the dos version)

All confirmed, thanks for the report!

**Comment by AcceptableSpare** [comment]
You're welcome! Sorry for editing the post so much, my writing sucks v:

**Comment by Interrupt** [comment]
RE: Transparency issues: so far we're setting both color 0 (black?) and color 0xFF (transparent?) to have transparent alpha, might need to just pick one of those to be black and one to be transparent and then go fix all the `gr_clear` commands to use the correct color in all cases.

**Comment by inguin** [comment]
Good idea! Sprites, doors, etc. use 0x00 for transparent areas, but that doesn't necessarily mean it must be transparent in `gamePalette`. We could use a special palette when converting bitmaps with the `BMF_TRANS` flag.
Most transparency issues are caused when blitting the `drawSurface` with all the HUD and text over the GL-rendered 3D view. Unfortunately the HUD border seems to contain both 0x00 and 0xFF pixels.

**Comment by Interrupt** [comment]
I wonder if color `0x00` is meant to be transparent knowing that. Back when I was getting software mode working for the first time there was a problem where the `0xFF` color used for the main `gr_clear` everywhere was a weird yellow and was showing up in the borders behind the HUD elements. You can see that issue in action here:

dbhklk0u0aaeoef

**Comment by inguin** [comment]
The Laser safety override screen shows in a very similar yellow (color 0xE2) in the software-renderer. It's invisible in OpenGL and supposed to be black.

screenshot_20180726_084946

**Comment by Interrupt** [comment]
@inguin that's a neat solution for the transparency issues!

I think the last issue I noticed with the rendering now is that the emissive parts of a texture are missing, visible in any texture that uses the palette effects to flash lights. I'm not sure what drives this in the software side to skip getting shaded by lighting, but if we could figure that out we could encode that data in the alpha channel probably for use in the shader.

**Comment by inguin** [comment]
Oooh, good catch! I never noticed these palette effects. Judging by the rendered pixel data and the contents of `SHADTABL.DAT` the first 32 colors are used for palette effects and not shaded (except color 0x02, for some reason). I think I know how to replicate that in GL.

**Comment by Interrupt** [comment]
You work fast! I think this is getting close to the point where we could merge this PR into master.
Things that would be nice first:
- Add option in the graphics menu to toggle OpenGL on and off, default to off?
- Externalize the shaders to files in a new shaders/ folder.

**Comment by inguin** [comment]
What exactly do you mean with externalizing the shaders?

1. Move the string constants to separate C files?
2. Raw .glsl files that are somehow compiled into the binary? Might require some scripting.
3. Loading the shaders at runtime? Adds more data files that the user needs to take care of, probably not worth the effort for those few lines.

Any chance we could use C++11? The raw string literals were very convenient.

**Comment by TobiasKarnat** [comment]
Example filtered textures and models: https://imgur.com/a/rkan7Gb

**Comment by Interrupt** [comment]
This seems like it's basically ready to get merged at this point. Anything else that should be done before then?

**Comment by inguin** [comment]
I agree, this is ready to be merged. I've been playing this quite a lot in the past week; there are still glitches, but no show-stoppers. I'll create separate issues for the remaining tasks.

**Comment by Interrupt** [comment]
Looked at this today on OSX and it had a bunch of weird OpenGL context issues, opened a PR that lets the SDLRenderer and the level renderer to share one context between themselves: https://github.com/inguin/systemshock/pull/11

**Comment by Interrupt** [comment]
Boom, merging!

**Pull request merged**
