### PR TITLE
Add native MIDI support for Linux

### PR DESCRIPTION
**Pull request by HunterZ**
Implemented Linux support for native MIDI music driver, via the ALSA sequencer API.

Tested in an Ubuntu VM with various software synthesizers that provide ALSA sequencer devices (Fluidsynth via Qsynth, Timidity, Yoshimi).

### CODE REVIEW

**Comment by Interrupt** [comment]
Could we skip showing the slider for the soundfont if there's only one found?

**Comment by HunterZ** [comment]
> Could we skip showing the slider for the soundfont if there's only one found?

Yes, but please try it both ways first and confirm which way you want to go.

In wrapper.c change `if (midiOutputCount > 0)` to `if (midiOutputCount > 1)` to suppress the slider when the current music device reports only one output.

**Comment by Interrupt** [comment]
I think it's much better without the slider if there's nothing to change it to - the whole slider as a selection thing is kind of janky but if it's an edge case then I'm much happier with it.

Thinking more about this, is there a way to just draw out the current soundfont as text without a slider if it's the only one found?

**Comment by HunterZ** [comment]
I agree that the slider method is not ideal and would be happy if someone were to implement a better widget.

I don't know if it's possible to just draw the current output with no slider when there's only one available.

For now I'll just change it to only show when there are 2 or more outputs, and we can revisit later if better UI options become available.

**Comment by HunterZ** [comment]
Update: Got it to show a reasonable text label when only one output is available.

**Pull request merged**
