### PR TITLE
Use enums instead of defines for synth settings

### PR DESCRIPTION
**Pull request by Oreo639**
I feel this is a cleaner way of doing it. If you disagree, let me know.

### CODE REVIEW

**Comment by HunterZ** [comment]
I like your enum solution better, although it's less consistent with the rest of the codebase.

**Comment by Oreo639** [comment]
What's with 
```
make[1]: *** [CMakeFiles/systemshock.dir/rule] Error 2
make: *** [systemshock] Error 2
```

**Comment by HunterZ** [comment]
@Oreo639 I see two errors:
```In file included from /Users/travis/build/Interrupt/systemshock/build_ext/fluidsynth-lite/src/utils/fluid_sys.c:24:
/Users/travis/build/Interrupt/systemshock/build_ext/fluidsynth-lite/src/utils/apple/timing_mach.h:22:6: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
#if (TIMING_MACH_BEFORE_10_12)
     ^
/Users/travis/build/Interrupt/systemshock/build_ext/fluidsynth-lite/src/utils/apple/timing_mach.h:9:35: note: expanded from macro 'TIMING_MACH_BEFORE_10_12'
#define TIMING_MACH_BEFORE_10_12 (defined(__MACH__) && __MAC_OS_X_VERSION_MIN_REQUIRED < 101200)
                                  ^
1 error generated.```

...and...

```/Users/travis/build/Interrupt/systemshock/src/GameSrc/wrapper.c:373:14: error: use of undeclared identifier 'REF_STR_FluidSyn'
        case REF_STR_FluidSyn: return "FluidSynth";
             ^```

**Comment by Oreo639** [comment]
> I see two errors:
First one seems like it is unrelated to my pr.
Second one, you are right I am a dummy.

**Comment by Interrupt** [comment]
Looks like this has a merge conflict now, @Oreo639 want to fix?

**Comment by Oreo639** [comment]
Thanks for reminding me.

**Pull request merged**
