### PR TITLE
Remove FindSDL2 scripts in favor of using our own

### PR DESCRIPTION
**Pull request by mrikola**
This might break some crossplatform compatibility, so we ought to test it well.

Also I'm turning the AppVeyor caching back on :)

### CODE REVIEW

**Comment by Interrupt** [comment]
Looks like Travis is having build issues with this: https://travis-ci.org/Interrupt/systemshock/jobs/471183661#L1082

**Comment by mrikola** [comment]
As discussed on Discord, I tried to modify the scripts on Linux/OSX in a way that the build script would generate a `lib/` folder which would then be added to the library path prior to running by a `run.sh`.

Travis doesn't create a downloadable artifact by default, though, so I guess I can't test the distributable myself.

**Comment by markkurikola** [comment]
Merged master into this as it contains the fluidsynth build, and it was causing a conflict.

**Comment by markkurikola** [comment]
And now it should actually compile with fluidsynth 😂

**Pull request merged**
